### ISSUE TITLE
Re-calibrate Nebulae

### ISSUE THREAD

**Issue by Airell** [Qu-Bit-Electronix/QB_Nebulae_V2#24]
In all instruments, stock GranularLooper and custom instruments, I have to 'boost' my 1v/oct signal to have the Neb 'convert' this to a value of +0.2 gkpitch and get a correct octave higher in the Csound processing. Applying 'Pitch Press transpose' is spot on 1v/oct (or 0.2 gkpitch).

I have to multiply my signal ~1.037 times before it's at the correct pitch. (1v = 1.037v, 2v = 2.074v etc). This can be done with an attenuverter which can boost a signal (ALM O/A/x2).

Re-calibration (holding Pitch on startup and wait for the yellow animation) does not solve the issue.

Attached a 'test instrument' producing a sine wave C3 ate 0v. When I apply 1v to the 1v/oct, the resulting sine is -20cents to low (-40cents at 2v etc...)

Can this be 'solved' by changing a config on the Neb's SD 'os' card? As similar methods to exist for othet digital modules?

[testC.zip](https://github.com/Qu-Bit-Electronix/QB_Nebulae_V2/files/7374800/testC.zip)

**Comment by Airell** [comment]
[130_8128Hz_sine.zip](https://github.com/Qu-Bit-Electronix/QB_Nebulae_V2/files/7383406/130_8128Hz_sine.zip)
Attached the sine I use to test the Granular Looper (Blend set to CCW).

**Comment by stephenhensley** [comment]
Hi @Airell thanks for reporting this.

The internal calibration (via holding pitch at bootup) sets the 0V points for the CV inputs -- this makes it so that things like pressing the buttons, will always return the nebulae to the original pitch/speed settings when no CV is applied.

The v/oct scaling is handled separately, and explicitly within [control.py](https://github.com/Qu-Bit-Electronix/QB_Nebulae_V2/blob/master/Code/nebulae/control.py#L232-L244).

For adjusting this for your needs, there are two approaches that could work.

1. The simplest option, that will get things tracking on your specific hardware: is to adjust the offset/scaling values to correct for the error you're seeing (a slight decrease in scaling looks like it might be enough for the error you're seeing).
2. A more complete, but complex solution would be to add a calibration mode to the module that requires patching in external voltage (typically 1V / 3V for a similar calibration routine). We would want to save this data with the calibrated offsets to access it between power cycles.

**Comment by Airell** [comment]
Hello @stephenhensley ,

Thank you very much! I was already looking into control.py, but it was to 'hardware-ish' for me to exactly know where to look. I have done a lot of programming over the years (and I'm very familiar with Linux), so this was quite easy when you pointed to the 'hybrid' function direction.

I have changed line 241 to adjust the '0.8685' value, but I had to increase it. One +1v was 20 cents to low for an octave, so I multiplied it with '1,01695'. Which is the number of cents in an octave (1200), divided by '1200 minus those missing 20 cents':

241: self.scaling = 0.8685 * (1200 / (1200 - 20))

For a solution in between, one might could add a config file on the USB stick which holds the number of 'missing' cents.
Option two would take me to much time to implement... developing and debugging on the Neb would take me to much time to set up. Thank god the python code is compiled every time the Neb is started :D !

Thanks again, and it saves a Nebulae round trip to/from the Netherlands/US, as I was about to ask you to repair the unit ;)

Cheers, Airell.

PS. I hope you could have a look at my new Alternate Instrument 'Avalon' #23 .

**Comment by stephenhensley** [comment]
@Airell glad to hear you were able to come to a solution that works for you!

If you're ssh-ing into the nebulae to edit the files, and not just editing files on the SD Card, you can relaunch the nebulae service by running `sudo systemctl restart nebulae.service`  (might save some time while you're messing around in the future 😄 )

And sure, I can take a look at your PRs over the next few days.

**Comment by Airell** [comment]
Ah thanks! Does the Nebulae (or the rPi actually) get a DHCP address or is it fixed? I found the credentials to be alarm/alarm .
Anyways, I'm happy with the 'custom calibration'. For now, back to making music 😄
